image_rgb = imread('1.jpg');
imageDetectBlack = image_rgb;
image1 = image_rgb(:,:,1);
image2 = image_rgb(:,:,2);
image3 = image_rgb(:,:,3) < 50;
mask = image1 & image2 & image3;
%se = strel('line',20,20);
%mask = imdilate(mask,se);
se = strel('disk',10);
mask = imclose(mask,se);
rp_cylinder = regionprops(mask, 'Area', 'Centroid', 'Circularity');
figure(1);
imshow(mask);

image_rgb = imread('2.jpg');
imageDetectBlack = image_rgb;
image1 = image_rgb(:,:,1);
image2 = image_rgb(:,:,2);
image3 = image_rgb(:,:,3) < 50;
mask = image1 & image2 & image3;
%se = strel('line',20,20);
%mask = imdilate(mask,se);
se = strel('disk',10);
mask = imclose(mask,se);
rp_sphere = regionprops(mask, 'Area', 'Centroid', 'Circularity');
figure(2);
imshow(mask);

image_rgb = imread('4.jpg');
imageDetectBlack = image_rgb;
image1 = image_rgb(:,:,1);
image2 = image_rgb(:,:,2);
image3 = image_rgb(:,:,3) < 50;
mask = image1 & image2 & image3;
%se = strel('line',20,20);
%mask = imdilate(mask,se);
se = strel('disk',10);
mask = imclose(mask,se);
rp_rec = regionprops(mask, 'Area', 'Centroid', 'Circularity');
figure(3);
imshow(mask);